// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kztphpglaukqmnjoyvne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6dHBocGdsYXVrcW1uam95dm5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTI0MjgsImV4cCI6MjA1ODU2ODQyOH0.mM_wTBNxVgdBgUFTeNmX9v3JFe6VFp8l6M1Jhi2nvNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);